
XCOPY /y /s /d "W:\CRM\CONFIGURACAO\"*.* "C:\Backup\"

REM XCOPY /v "X:\htdocs\"*.* "C:\BackupXampp\htdocs\"
REM XCOPY /v "X:\htdocs\configuracao\"*.* "C:\BackupXampp\htdocs\configuracao\"
REM XCOPY /v "X:\htdocs\configuracao\alimentadores\"*.* "C:\BackupXampp\htdocs\configuracao\alimentadores\"
REM XCOPY /v "X:\htdocs\configuracao\arquivos\"*.* "C:\BackupXampp\htdocs\configuracao\arquivos\"
REM XCOPY /v "X:\htdocs\configuracao\bootstrap\"*.* "C:\BackupXampp\htdocs\configuracao\bootstrap\"
REM XCOPY /v "X:\htdocs\configuracao\css\"*.* "C:\BackupXampp\htdocs\configuracao\css\"
REM XCOPY /v "X:\htdocs\configuracao\fonts\"*.* "C:\BackupXampp\htdocs\configuracao\fonts\"
REM XCOPY /v "X:\htdocs\configuracao\images\"*.* "C:\BackupXampp\htdocs\configuracao\images\"
REM XCOPY /v "X:\htdocs\configuracao\include\"*.* "C:\BackupXampp\htdocs\configuracao\include\"
REM XCOPY /v "X:\htdocs\configuracao\js\"*.* "C:\BackupXampp\htdocs\configuracao\js\"
REM XCOPY /v "X:\htdocs\configuracao\plugins\"*.* "C:\BackupXampp\htdocs\configuracao\plugins\"
REM XCOPY /v "X:\htdocs\configuracao\plugins\"*.* "C:\BackupXampp\htdocs\configuracao\plugins\"
REM XCOPY /v "X:\htdocs\configuracao\reports\"*.* "C:\BackupXampp\htdocs\configuracao\reports\"
REM XCOPY /v "X:\htdocs\configuracao\reports\gerais\"*.* "C:\BackupXampp\htdocs\configuracao\reports\gerais\"
